name: Build Electron App for Windows and macOS

on:
  push:
    branches: [master]

jobs:
  build_on_mac:
    runs-on: macos-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
          node-version: 10.24.1
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn make

  build_on_win:
    runs-on: windows-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
          node-version: 10.24.1
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn make
