name: Build Electron App for Windows and macOS

on:
  push:
    branches: [master]

jobs:
  build_on_mac:
    runs-on: macos-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
          node-version: 16.17.0
      - name: set openssl
        run: ln -s /usr/local/Cellar/openssl/[version]/include/openssl
      - name: set openssl2
        run: ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
      - name: install dependencies
        run: yarn install --ignore-engines
      - name: build
        run: yarn make

  build_on_win:
    runs-on: windows-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
          node-version: 16.17.0
      - name: set openssl
        run: New-Item -ItemType SymbolicLink -Path "C:\usr\local\lib\libssl.1.0.0.dylib" -Target "C:\usr\local\opt\openssl\lib\libssl.1.0.0.dylib"
      - name: set openssl2
        run: New-Item -ItemType SymbolicLink -Path "C:\usr\local\Cellar\openssl[version]\include\openssl" -Target "C:\usr\local\Cellar\openssl[version]\include\openssl"
      - name: install dependencies
        run: yarn install --ignore-engines
      - name: build
        run: yarn make
